# Generated by Django 6.0.3 on 2026-03-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('hashed', models.IntegerField(primary_key=True, serialize=False, verbose_name='ハッシュ値')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('source_url', models.URLField(max_length=500, verbose_name='取得元リンク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '画像データ',
                'verbose_name_plural': '画像データ',
                'db_table': 'image_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='グループ名')),
                ('idol_name', models.CharField(blank=True, max_length=200, verbose_name='アイドル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idol_info', to='images.imagedata', verbose_name='画像データ')),
            ],
            options={
                'verbose_name': 'アイドル情報',
                'verbose_name_plural': 'アイドル情報',
                'db_table': 'idol_info',
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=100, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='images.imagedata', verbose_name='画像データ')),
            ],
            options={
                'verbose_name': '画像タグ',
                'verbose_name_plural': '画像タグ',
                'db_table': 'image_tag',
                'indexes': [models.Index(fields=['tag_name'], name='image_tag_tag_nam_3e3a07_idx')],
                'unique_together': {('image', 'tag_name')},
            },
        ),
    ]
